### ISSUE TITLE
고정된 행에서 hover시 뒤의 배경이 투명화되는 문제 해결하기

### ISSUE THREAD

**Issue by yeongjong310** [wantedPreOnboarding/19_06th_cola_dashboard#33]
![2](https://user-images.githubusercontent.com/76679130/156364559-d8b99310-39b4-4c8a-b7ee-cf2517056b89.png)
![1](https://user-images.githubusercontent.com/76679130/156364567-67dd854a-fdb1-4647-aadf-573d38fd94e3.png)

**Comment by leechoiswim1** [comment]
만약 체크박스를 선택한 행이 sticky될때 뒤에배경이 투명해지고 체크박스 해제시 뒤 체크박스가 동시클릭되는 버그라면 송현님 올려주신 MUITableRow에 호버 background 추가 하는 것과     
<M.MUITableRow
      // hover={hover}
      {...(stickyTop !== undefined && {
        sx: { position: 'sticky', zIndex: 100, top: stickyTop, ...sx },
      })}
      onClick={() => (isHeader ? onClickHandler?.() : onClickHandler?.(order.orderId))}
    >
이 부분에서 zindex를 100을 주면 해결이 됩니다. 따로 호버 부분에 z-index를 안줘도 작동하는것을 확인했습니다.
